### ISSUE TITLE
Need option to propagate sensor errors

### ISSUE THREAD

**Issue by Krellan** [quanta-bmc/read-margin-temp#11]
I propose an enhancement to read-margin-temp.

It needs the option to propagate sensor errors.

Currently, read-margin-temp skips over any malfunctioning sensor, when read-margin-temp is collecting all of the sensor readings to find the combined worst-margin value.

Some designs require behavior that is intentionally less tolerant of errors. Namely, some designs require the fans be thrown into failsafe mode whenever a temperature sensor fails. Because there is no way to know how hot the component is, the system must assume the worst, and run the fans at high speed. This will also have the beneficial side effect of getting the operator's attention, as the noise from high speed fans might tell them a component has failed internally.

So, what I propose is this: When collecting sensors, report the final value over D-Bus as floating-point "NaN" if there is any error. Then, clients of this value, such as the phosphor-pid-control program for managing fan speed, can detect this "NaN" and use it to know to put the fans into failsafe mode. Since the program is already using floating-point values, this gives it the ability to indicate "none of the above" with "NaN", which is cleaner than indicating a false hardcoded value of 0 or -1 or 99 or other sentinel value that could actually be a valid reading under some circumstances.

There are at least these conditions that should result in error propagation:

* File IO error from open() of a sensor file on the filesystem
* File IO error upon read() of a sensor file on the filesystem
* Parsing error when trying to convert the file text to a floating-point number
* D-Bus error upon trying to read a sensor value over D-Bus
* The resulting floating-point number is not numeric (+Inf, -Inf, NaN)

To avoid breaking existing clients, this behavior will be optional. The default will be to silently ignore errors, as before. A command line such as --strict or --brittle will be used, to get this error propagation behavior (I am open to naming suggestions). Your thoughts?

**Comment by harveyquta** [comment]
Sound good, this will be useful in some situation. I will try to implement this function. Thanks.

**Comment by harveyquta** [comment]
Hi Krellan,
Current phosphor-pid-control seems not detect "HostSensor" failed. Because when I create the HostSensor via pid-control, and set NaN value to the HostSensor dbus. phosphor-pid-control not into failsafe mode to 100% immediatly but increase PWM duty slowly. 
After view the source code, looks like didn't implement getFailed() function in host.cpp, so when getFailed() in [pid/zone.cpp](https://github.com/openbmc/phosphor-pid-control/blob/master/pid/zone.cpp#L378), it will return [false](https://github.com/openbmc/phosphor-pid-control/blob/master/sensors/sensor.hpp#L47). After I add the code below, when I set the NaN value to HostSensor dbus, phosphor-pid-control is into failsafe mode immediatly.
bool HostSensor::getFailed(void)
{
    if (!(std::isfinite(_value)))
    {
        return true;
    }
    else
    {
        return false;
    }
}

**Comment by Krellan** [comment]
Nice, your commit looks good. I didn't think of checking the Functional property of sensors, so that's good. Our work will not overlap. I'm checking for errors in other ways (mentioned in the bullet-points in my original proposal above).

As for phosphor-pid-control, good catch about host sensors. I don't use host sensors, I only use D-Bus passive sensors. You should send that in to phosphor-pid-control Gerrit, as a change. It will be useful to those who use host sensors.

FYI, I have some other patches that do some other miscellaneous cleanups in phosphor-pid-control but they have not been accepted upstream yet. You might want to look at them, some might be helpful. Here are the patches: https://gerrit.openbmc-project.xyz/q/project:openbmc/phosphor-pid-control+author:krellan%2540google.com+status:open

**Comment by harveyquta** [comment]
Thanks, I will push a commit to phosphor-pid-control Gerrit.
Additionally, I have a question about phosphor-pid-control. The current [dbusconfiguration.cpp](https://github.com/openbmc/phosphor-pid-control/blob/master/dbus/dbusconfiguration.cpp#L639), it seems not support "margin" type, only detect type "fan" and "temp" in entity-manager json. Is there any reason to not support "margin" type?

**Comment by harveyquta** [comment]
OK, I saw your commit in Gerrit. Sorry for not checking commit before asking question.

**Comment by Krellan** [comment]
I have added this pull request: https://github.com/quanta-bmc/read-margin-temp/pull/12

Take a look at the TODO items in the commit message. I think this pull request will stack nicely with your other change. I like how you added a proper command-line parser in your change.

**Comment by harveyquta** [comment]
I push the new branch which merge your PR. Is that fit the requirements? Or have something that I forgot to add?
Thanks.

**Comment by Krellan** [comment]
Thanks for merging it! I looked over it and wrote some comments here.

https://github.com/quanta-bmc/read-margin-temp/commit/9d4847a9d1a080a0f5a32cd1c5aa2ed6968c3d0f#

Basically, my only concern is that "debugEnabled" got lost. It needs to be
a variable. Instead, constant DEBUG is still in use, which was from an
older version.

Thanks!
Josh

Josh Lehan | Software Engineer | krellan@google.com | +1 650-733-8941

**Comment by harveyquta** [comment]
Hi Krellan, I have been commit the newest PR #13 .

**Comment by Krellan** [comment]
Nice, thanks! I looked at
https://github.com/quanta-bmc/read-margin-temp/pull/13 and left some review
comments.

Josh

Josh Lehan | Software Engineer | krellan@google.com | +1 650-733-8941
